//
// UserResponseFieldsCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserResponseFieldsCollection: JSONEncodable {
    public var items: [UserResponseFields]?
    public var nextPageToken: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["nextPageToken"] = self.nextPageToken
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
