//
// UserRequestFields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserRequestFields: JSONEncodable {
    public var birthDate: String?
    public var description: String?
    public var email: String?
    public var gender: String?
    public var hasNest: Bool?
    public var homeLocation: String?
    public var isLatexAllergic: Bool?
    public var isStrokee: Bool?
    public var isStroker: Bool?
    public var nickname: String?
    public var phone: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["birth_date"] = self.birthDate
        nillableDictionary["description"] = self.description
        nillableDictionary["email"] = self.email
        nillableDictionary["gender"] = self.gender
        nillableDictionary["has_nest"] = self.hasNest
        nillableDictionary["home_location"] = self.homeLocation
        nillableDictionary["is_latex_allergic"] = self.isLatexAllergic
        nillableDictionary["is_strokee"] = self.isStrokee
        nillableDictionary["is_stroker"] = self.isStroker
        nillableDictionary["nickname"] = self.nickname
        nillableDictionary["phone"] = self.phone
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
